run:
	go run main.go
run-container:
	docker-compose -f docker-compose.dev.yml up -d
stop-container:
	docker-compose -f docker-compose.dev.yml stop
delete-container:
	docker-compose -f docker-compose.dev.yml rm